name: CI - Pull Requests to Main

on:
  pull_request:
    branches: [main]
    types: [opened, reopened, synchronize]
jobs:
  test-integration:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run integration tests
        run: npm run test:integration

      - name: Notify Slack
        if: always()
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
          PR_TITLE: ${{ github.event.pull_request.title }}
          PR_URL: ${{ github.event.pull_request.html_url }}
          JOB_STATUS: ${{ job.status }}
        run: |
          STATUS_EMOJI=""
          MESSAGE=""

          if [ "$JOB_STATUS" == "success" ]; then
            STATUS_EMOJI=":white_check_mark:"
            MESSAGE="Integration tests passed successfully"
          elif [ "$JOB_STATUS" == "failure" ]; then
            STATUS_EMOJI=":x:"
            MESSAGE="Integration tests failed"
          else
            STATUS_EMOJI=":warning:"
            MESSAGE="Job was cancelled or ended unexpectedly"
          fi

          curl -X POST -H 'Content-type: application/json' --data "{
            \"channel\": \"#otro-canal\",
            \"attachments\": [{
              \"color\": \"#36a64f\",
              \"title\": \"PR #$PR_NUMBER - $PR_TITLE\",
              \"title_link\": \"$PR_URL\",
              \"text\": \"$MESSAGE $STATUS_EMOJI\"
            }]
          }" $SLACK_WEBHOOK